export const context = {
  name: 'Иван',
  inputs: [
    {
      name: 'email',
      label: 'Почта',
      value: 'pochta@yandex.ru',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },
    {
      name: 'login',
      label: 'Логин',
      value: 'ivanivanov',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },
    {
      name: 'first_name',
      label: 'Имя',
      value: 'Иван',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },
    {
      name: 'second_name',
      label: 'Фамилия',
      value: 'Иванов',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },

    {
      name: 'display_name',
      label: 'Имя в чате',
      value: 'Иван',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },
    {
      name: 'phone',
      label: 'Телефон',
      value: '+79099673030',
      type: 'text',
      error: '',
      required: true,
      disabled: true,
    },
  ],
  //   avatar: '',
  //   oldPassword: '',
  //   newPassword: '',
  buttons: [
    {
      type: 'button',
      name: 'changeData',
      title: 'Изменить данные',
      class: 'secondary',
    },
    {
      type: 'button',
      name: 'changePassword',
      title: 'Изменить пароль',
      class: 'secondary',
    },
    {
      type: 'button',
      name: 'signOut',
      title: 'Выйти',
      class: 'danger',
    },
  ],
};
